texts = {
    "welcome": "👋 Assalomu alaykum!\n\nBu bot orqali o‘z daromad va xarajatlaringizni nazorat qilishingiz mumkin.",
    "main_menu": "🏠 Asosiy menyu:",
    "add_menu": "➕ Qaysi turdagi yozuv qo‘shmoqchisiz?",
    "report_menu": "📊 Qaysi davr uchun hisobot kerak?",
    "back": "🔙 Orqaga qaytdingiz.",
    "income_added": "💰Daromad muvaffaqiyatli qo‘shildi!",
    "expense_added": "💸Xarajat muvaffaqiyatli qo‘shildi!",
    "enter_amount": "💰 Miqdorni kiriting (so‘mda):",
    "enter_description": "📝 Izoh kiriting (ixtiyoriy):",
    "error": "❗️ Xatolik yuz berdi. Qaytadan urinib ko‘ring.",
    "cancelled": "❌ Bekor qilindi.",
    "choose_category": "📂 Kategoriyani tanlang:",
    "monthly_summary": "🗓 Oylik umumiy hisobot:",
    "daily_summary": "📅 Bugungi umumiy hisobot:",
    "no_data": "ℹ️ Hali hech qanday yozuv yo‘q.",
    "settings_menu": "⚙️ Sozlamalar bo‘limi:",
    "usd_rate": "💱 Bugungi USD kursi: {} so‘m",
}